ARG NODE_VERSION=22.14 LINUX_VERSION="slim"
FROM node:${NODE_VERSION}${LINUX_VERSION:+-$LINUX_VERSION} AS build

WORKDIR /frontend

COPY --link package.json bun.lock /frontend/

RUN npm install -g bun
RUN bun install --frozen-lockfile

FROM node:${NODE_VERSION}${LINUX_VERSION:+-$LINUX_VERSION} AS development

COPY --from=build /frontend/node_modules /frontend/node_modules

WORKDIR /frontend

RUN npm install -g bun

CMD ["bun", "dev"]