[project]
name = "app"
version = "0.1.0"
description = ''
license = { text = "MIT" }
requires-python = ">=3.13"
dependencies = [
  "fastapi[standard]==0.116.*",
  "tenacity==9.*",
  "emails==0.6.*",
  "alembic==1.15.*",
  "sqlmodel==0.0.*",
  "python-multipart==0.0.*",
  "email-validator==2.*",
  "psycopg[binary]==3.2.*",
  "pydantic_settings==2.*",
  "fastapi-myauth==1.*",
  "openai>=2.0.0",
  "celery>=5.5.3",
  "redis",
  "celery-redbeat",
]

[dependency-groups]
dev = [
  "ruff>=0.12.8",
  "pytest<8.0.0,>=7.4.3",
  "coverage<8.0.0,>=7.4.3",
  "freezegun>=1.5.1",
  "pre-commit<4.0.0,>=3.6.2",
]

[tool.ruff]
target-version = "py313"
exclude = ["alembic"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG001", # unused arguments in functions
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "B904",  # Allow raising exceptions without from e, for HTTPException
]

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.semantic_release]
commit_parser = "conventional"
tag_format = "v{version}"
version_toml = ["pyproject.toml:project.version"]
