"""Initial Commit

Revision ID: 66160a9ae8d8
Revises: 
Create Date: 2026-06-08 00:09:02.101127

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '66160a9ae8d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_validated', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('totp_counter', sa.Integer(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('passkeyceremony',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('challenge', sa.LargeBinary(), nullable=False),
    sa.Column('ceremony_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passkeyceremony_ceremony_type'), 'passkeyceremony', ['ceremony_type'], unique=False)
    op.create_index(op.f('ix_passkeyceremony_expires_at'), 'passkeyceremony', ['expires_at'], unique=False)
    op.create_index(op.f('ix_passkeyceremony_user_id'), 'passkeyceremony', ['user_id'], unique=False)
    op.create_table('passkeycredential',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(length=1023), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('backed_up', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passkeycredential_credential_id'), 'passkeycredential', ['credential_id'], unique=True)
    op.create_index(op.f('ix_passkeycredential_user_id'), 'passkeycredential', ['user_id'], unique=False)
    op.create_table('refreshtoken',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authenticates_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['authenticates_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('socialaccount',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_social_account_provider_subject'),
    sa.UniqueConstraint('provider', 'user_id', name='uq_social_account_provider_user')
    )
    op.create_index(op.f('ix_socialaccount_provider'), 'socialaccount', ['provider'], unique=False)
    op.create_index(op.f('ix_socialaccount_user_id'), 'socialaccount', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_socialaccount_user_id'), table_name='socialaccount')
    op.drop_index(op.f('ix_socialaccount_provider'), table_name='socialaccount')
    op.drop_table('socialaccount')
    op.drop_table('refreshtoken')
    op.drop_index(op.f('ix_passkeycredential_user_id'), table_name='passkeycredential')
    op.drop_index(op.f('ix_passkeycredential_credential_id'), table_name='passkeycredential')
    op.drop_table('passkeycredential')
    op.drop_index(op.f('ix_passkeyceremony_user_id'), table_name='passkeyceremony')
    op.drop_index(op.f('ix_passkeyceremony_expires_at'), table_name='passkeyceremony')
    op.drop_index(op.f('ix_passkeyceremony_ceremony_type'), table_name='passkeyceremony')
    op.drop_table('passkeyceremony')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
